plugins {
    id 'io.micronaut.build.internal.session-base'
    id 'java'
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(projects.micronautSession)

    testImplementation mn.reactor
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.http.server)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mnSerde.micronaut.serde.jackson)
    testRuntimeOnly(mnTest.junit.platform.suite)

    testRuntimeOnly mnLogging.logback.classic
}

test {
    useJUnitPlatform()
}
