[versions]
micronaut = "4.0.0-M2"
micronaut-cache = "4.0.0-M1"
micronaut-docs = "2.0.0"
micronaut-serde = "2.0.0-M1"
micronaut-test = "4.0.0-M1"

groovy = "4.0.10"
junit = '5.9.2'
kotest = '5.5.5'
kotlin = '1.8.20'
spock = "2.3-groovy-4.0"

[libraries]
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }

junit-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit' }
kotest = { module = 'io.kotest:kotest-runner-junit5', version.ref = 'kotest' }
kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = 'kotlin' }
kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[bundles]

[plugins]
kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }
kotlin-kapt = { id = 'org.jetbrains.kotlin.kapt', version.ref = 'kotlin' }
