[versions]
micronaut = "4.0.0-SNAPSHOT"
micronaut-cache = "4.0.0-SNAPSHOT"
micronaut-docs = "2.0.0"
micronaut-serde = "2.0.0-SNAPSHOT"
micronaut-test = "4.0.0-SNAPSHOT"
groovy = "4.0.6"
spock = "2.3-groovy-4.0"

[libraries]
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }

[bundles]

[plugins]
